"""Initial migration with all tables

Revision ID: cf3d5b32a1e3
Revises: 
Create Date: 2025-11-18 18:19:20.039307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf3d5b32a1e3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('county', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cities_enabled'), 'cities', ['enabled'], unique=False)
    op.create_index(op.f('ix_cities_id'), 'cities', ['id'], unique=False)
    op.create_index(op.f('ix_cities_slug'), 'cities', ['slug'], unique=True)
    op.create_index(op.f('ix_cities_state'), 'cities', ['state'], unique=False)
    op.create_table('request_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.String(), nullable=False),
    sa.Column('method', sa.String(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('response_time_ms', sa.Float(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_request_metrics_city'), 'request_metrics', ['city'], unique=False)
    op.create_index(op.f('ix_request_metrics_created_at'), 'request_metrics', ['created_at'], unique=False)
    op.create_index(op.f('ix_request_metrics_endpoint'), 'request_metrics', ['endpoint'], unique=False)
    op.create_index(op.f('ix_request_metrics_id'), 'request_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_request_metrics_status_code'), 'request_metrics', ['status_code'], unique=False)
    op.create_table('source_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('source_name', sa.String(), nullable=True),
    sa.Column('parser_version', sa.String(), nullable=True),
    sa.Column('parser_name', sa.String(), nullable=True),
    sa.Column('total_records_extracted', sa.Integer(), nullable=True),
    sa.Column('successful_records', sa.Integer(), nullable=True),
    sa.Column('failed_records', sa.Integer(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('last_fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_parsed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_metadata_city'), 'source_metadata', ['city'], unique=False)
    op.create_index(op.f('ix_source_metadata_id'), 'source_metadata', ['id'], unique=False)
    op.create_table('addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('normalized_address', sa.String(), nullable=False),
    sa.Column('house_number', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('city_slug', sa.String(), nullable=True),
    sa.Column('city_name', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('zip_code', sa.String(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('official_trash_day', sa.String(), nullable=True),
    sa.Column('official_recycling_day', sa.String(), nullable=True),
    sa.Column('official_green_day', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_addresses_city_id'), 'addresses', ['city_id'], unique=False)
    op.create_index(op.f('ix_addresses_city_name'), 'addresses', ['city_name'], unique=False)
    op.create_index(op.f('ix_addresses_city_slug'), 'addresses', ['city_slug'], unique=False)
    op.create_index(op.f('ix_addresses_id'), 'addresses', ['id'], unique=False)
    op.create_index(op.f('ix_addresses_normalized_address'), 'addresses', ['normalized_address'], unique=False)
    op.create_index(op.f('ix_addresses_state'), 'addresses', ['state'], unique=False)
    op.create_index(op.f('ix_addresses_street'), 'addresses', ['street'], unique=False)
    op.create_index(op.f('ix_addresses_zip_code'), 'addresses', ['zip_code'], unique=False)
    op.create_table('pickup_zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('external_ref', sa.String(), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pickup_zone_city_ref', 'pickup_zones', ['city_id', 'external_ref'], unique=False)
    op.create_index(op.f('ix_pickup_zones_city_id'), 'pickup_zones', ['city_id'], unique=False)
    op.create_index(op.f('ix_pickup_zones_id'), 'pickup_zones', ['id'], unique=False)
    op.create_table('address_pickup_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address_id', sa.Integer(), nullable=False),
    sa.Column('pickup_zone_id', sa.Integer(), nullable=True),
    sa.Column('trash_day_of_week', sa.String(), nullable=True),
    sa.Column('recycling_day_of_week', sa.String(), nullable=True),
    sa.Column('green_day_of_week', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['addresses.id'], ),
    sa.ForeignKeyConstraint(['pickup_zone_id'], ['pickup_zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_address_pickup_zone', 'address_pickup_info', ['address_id', 'pickup_zone_id'], unique=False)
    op.create_index(op.f('ix_address_pickup_info_address_id'), 'address_pickup_info', ['address_id'], unique=True)
    op.create_index(op.f('ix_address_pickup_info_id'), 'address_pickup_info', ['id'], unique=False)
    op.create_index(op.f('ix_address_pickup_info_pickup_zone_id'), 'address_pickup_info', ['pickup_zone_id'], unique=False)
    op.create_table('crowd_consensus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address_id', sa.Integer(), nullable=False),
    sa.Column('consensus_trash_day', sa.String(), nullable=True),
    sa.Column('consensus_recycling_day', sa.String(), nullable=True),
    sa.Column('consensus_green_day', sa.String(), nullable=True),
    sa.Column('total_reports', sa.Integer(), nullable=True),
    sa.Column('trash_agreement_ratio', sa.Float(), nullable=True),
    sa.Column('recycling_agreement_ratio', sa.Float(), nullable=True),
    sa.Column('green_agreement_ratio', sa.Float(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['addresses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crowd_consensus_address_id'), 'crowd_consensus', ['address_id'], unique=True)
    op.create_index(op.f('ix_crowd_consensus_id'), 'crowd_consensus', ['id'], unique=False)
    op.create_index(op.f('ix_crowd_consensus_is_verified'), 'crowd_consensus', ['is_verified'], unique=False)
    op.create_table('crowd_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address_id', sa.Integer(), nullable=False),
    sa.Column('trash_day', sa.String(), nullable=True),
    sa.Column('recycling_day', sa.String(), nullable=True),
    sa.Column('green_day', sa.String(), nullable=True),
    sa.Column('user_hash', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['addresses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_address_created', 'crowd_reports', ['address_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_crowd_reports_address_id'), 'crowd_reports', ['address_id'], unique=False)
    op.create_index(op.f('ix_crowd_reports_created_at'), 'crowd_reports', ['created_at'], unique=False)
    op.create_index(op.f('ix_crowd_reports_id'), 'crowd_reports', ['id'], unique=False)
    op.create_index(op.f('ix_crowd_reports_ip_address'), 'crowd_reports', ['ip_address'], unique=False)
    op.create_index(op.f('ix_crowd_reports_user_hash'), 'crowd_reports', ['user_hash'], unique=False)
    op.create_table('schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('pickup_zone_id', sa.Integer(), nullable=True),
    sa.Column('trash_day_of_week', sa.String(), nullable=True),
    sa.Column('recycling_day_of_week', sa.String(), nullable=True),
    sa.Column('green_day_of_week', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['pickup_zone_id'], ['pickup_zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_schedule_city_zone', 'schedules', ['city_id', 'pickup_zone_id'], unique=False)
    op.create_index(op.f('ix_schedules_city_id'), 'schedules', ['city_id'], unique=False)
    op.create_index(op.f('ix_schedules_id'), 'schedules', ['id'], unique=False)
    op.create_index(op.f('ix_schedules_pickup_zone_id'), 'schedules', ['pickup_zone_id'], unique=False)
    op.create_table('schedule_exceptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=True),
    sa.Column('exception_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rescheduled_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_cancelled', sa.Boolean(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_exceptions_exception_date'), 'schedule_exceptions', ['exception_date'], unique=False)
    op.create_index(op.f('ix_schedule_exceptions_id'), 'schedule_exceptions', ['id'], unique=False)
    op.create_index(op.f('ix_schedule_exceptions_schedule_id'), 'schedule_exceptions', ['schedule_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schedule_exceptions_schedule_id'), table_name='schedule_exceptions')
    op.drop_index(op.f('ix_schedule_exceptions_id'), table_name='schedule_exceptions')
    op.drop_index(op.f('ix_schedule_exceptions_exception_date'), table_name='schedule_exceptions')
    op.drop_table('schedule_exceptions')
    op.drop_index(op.f('ix_schedules_pickup_zone_id'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_id'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_city_id'), table_name='schedules')
    op.drop_index('idx_schedule_city_zone', table_name='schedules')
    op.drop_table('schedules')
    op.drop_index(op.f('ix_crowd_reports_user_hash'), table_name='crowd_reports')
    op.drop_index(op.f('ix_crowd_reports_ip_address'), table_name='crowd_reports')
    op.drop_index(op.f('ix_crowd_reports_id'), table_name='crowd_reports')
    op.drop_index(op.f('ix_crowd_reports_created_at'), table_name='crowd_reports')
    op.drop_index(op.f('ix_crowd_reports_address_id'), table_name='crowd_reports')
    op.drop_index('idx_address_created', table_name='crowd_reports')
    op.drop_table('crowd_reports')
    op.drop_index(op.f('ix_crowd_consensus_is_verified'), table_name='crowd_consensus')
    op.drop_index(op.f('ix_crowd_consensus_id'), table_name='crowd_consensus')
    op.drop_index(op.f('ix_crowd_consensus_address_id'), table_name='crowd_consensus')
    op.drop_table('crowd_consensus')
    op.drop_index(op.f('ix_address_pickup_info_pickup_zone_id'), table_name='address_pickup_info')
    op.drop_index(op.f('ix_address_pickup_info_id'), table_name='address_pickup_info')
    op.drop_index(op.f('ix_address_pickup_info_address_id'), table_name='address_pickup_info')
    op.drop_index('idx_address_pickup_zone', table_name='address_pickup_info')
    op.drop_table('address_pickup_info')
    op.drop_index(op.f('ix_pickup_zones_id'), table_name='pickup_zones')
    op.drop_index(op.f('ix_pickup_zones_city_id'), table_name='pickup_zones')
    op.drop_index('idx_pickup_zone_city_ref', table_name='pickup_zones')
    op.drop_table('pickup_zones')
    op.drop_index(op.f('ix_addresses_zip_code'), table_name='addresses')
    op.drop_index(op.f('ix_addresses_street'), table_name='addresses')
    op.drop_index(op.f('ix_addresses_state'), table_name='addresses')
    op.drop_index(op.f('ix_addresses_normalized_address'), table_name='addresses')
    op.drop_index(op.f('ix_addresses_id'), table_name='addresses')
    op.drop_index(op.f('ix_addresses_city_slug'), table_name='addresses')
    op.drop_index(op.f('ix_addresses_city_name'), table_name='addresses')
    op.drop_index(op.f('ix_addresses_city_id'), table_name='addresses')
    op.drop_table('addresses')
    op.drop_index(op.f('ix_source_metadata_id'), table_name='source_metadata')
    op.drop_index(op.f('ix_source_metadata_city'), table_name='source_metadata')
    op.drop_table('source_metadata')
    op.drop_index(op.f('ix_request_metrics_status_code'), table_name='request_metrics')
    op.drop_index(op.f('ix_request_metrics_id'), table_name='request_metrics')
    op.drop_index(op.f('ix_request_metrics_endpoint'), table_name='request_metrics')
    op.drop_index(op.f('ix_request_metrics_created_at'), table_name='request_metrics')
    op.drop_index(op.f('ix_request_metrics_city'), table_name='request_metrics')
    op.drop_table('request_metrics')
    op.drop_index(op.f('ix_cities_state'), table_name='cities')
    op.drop_index(op.f('ix_cities_slug'), table_name='cities')
    op.drop_index(op.f('ix_cities_id'), table_name='cities')
    op.drop_index(op.f('ix_cities_enabled'), table_name='cities')
    op.drop_table('cities')
    # ### end Alembic commands ###
