"""
Updater Agent for the multi-agent data validation pipeline.

This agent is responsible for applying correction actions to the database.
"""

from typing import Dict, Any, List
from datetime import datetime
from sqlalchemy.orm import Session
from sqlalchemy.exc import SQLAlchemyError

from .base_agent import (
    BaseAgent, CorrectionAction, AgentStatus
)
from app.models import (
    Address, Schedule, PickupZone, ScheduleException, AddressPickupInfo
)


class UpdaterAgent(BaseAgent):
    """
    Agent responsible for applying correction actions to the database.

    This agent takes correction actions generated by the CorrectionAgent
    and applies them to the database, with proper error handling and
    transaction management.
    """

    # Mapping from entity type to model class
    MODEL_MAP = {
        'Address': Address,
        'Schedule': Schedule,
        'PickupZone': PickupZone,
        'ScheduleException': ScheduleException,
        'AddressPickupInfo': AddressPickupInfo
    }

    @property
    def agent_name(self) -> str:
        return "UpdaterAgent"

    def _execute(self, context: Dict[str, Any]) -> None:
        """
        Apply correction actions to the database.

        Expected context keys:
            - db_session: SQLAlchemy database session
            - correction_actions: List of CorrectionAction objects
            - dry_run: (Optional) If True, don't commit changes
            - batch_size: (Optional) Number of updates per transaction

        Sets in context:
            - applied_corrections: List of successfully applied corrections
            - failed_corrections: List of failed corrections
        """
        db_session: Session = context.get("db_session")
        if not db_session:
            raise ValueError("Database session required in context")

        correction_actions = context.get("correction_actions", [])
        dry_run = context.get("dry_run", False)
        batch_size = context.get("batch_size", 100)

        if not correction_actions:
            self.logger.info("No correction actions to apply")
            context["applied_corrections"] = []
            context["failed_corrections"] = []
            return

        self.logger.info(
            f"Applying {len(correction_actions)} corrections "
            f"({'DRY RUN' if dry_run else 'LIVE'})"
        )

        applied_corrections = []
        failed_corrections = []

        # Group corrections by action type for better logging
        updates = [c for c in correction_actions if c.action_type == "update"]
        deletes = [c for c in correction_actions if c.action_type == "delete"]
        creates = [c for c in correction_actions if c.action_type == "create"]

        self.logger.info(
            f"Corrections breakdown: {len(updates)} updates, "
            f"{len(deletes)} deletes, {len(creates)} creates"
        )

        # Process updates
        for correction in updates:
            try:
                self._apply_update(db_session, correction)
                applied_corrections.append(correction)
                self._add_correction(correction, applied=True)
            except Exception as e:
                self.logger.error(
                    f"Failed to apply update for {correction.entity_type} "
                    f"{correction.entity_id}: {str(e)}"
                )
                correction.executed = True
                correction.success = False
                correction.error_message = str(e)
                failed_corrections.append(correction)

        # Process deletes
        for correction in deletes:
            try:
                self._apply_delete(db_session, correction)
                applied_corrections.append(correction)
                self._add_correction(correction, applied=True)
            except Exception as e:
                self.logger.error(
                    f"Failed to apply delete for {correction.entity_type} "
                    f"{correction.entity_id}: {str(e)}"
                )
                correction.executed = True
                correction.success = False
                correction.error_message = str(e)
                failed_corrections.append(correction)

        # Process creates
        for correction in creates:
            try:
                self._apply_create(db_session, correction)
                applied_corrections.append(correction)
                self._add_correction(correction, applied=True)
            except Exception as e:
                self.logger.error(
                    f"Failed to apply create for {correction.entity_type}: {str(e)}"
                )
                correction.executed = True
                correction.success = False
                correction.error_message = str(e)
                failed_corrections.append(correction)

        # Commit or rollback
        if dry_run:
            self.logger.info("DRY RUN: Rolling back all changes")
            db_session.rollback()
        else:
            try:
                db_session.commit()
                self.logger.info(
                    f"Successfully committed {len(applied_corrections)} corrections"
                )
            except SQLAlchemyError as e:
                self.logger.error(f"Failed to commit changes: {str(e)}")
                db_session.rollback()
                # Mark all as failed
                for correction in applied_corrections:
                    correction.success = False
                    correction.error_message = f"Commit failed: {str(e)}"
                failed_corrections.extend(applied_corrections)
                applied_corrections = []
                self._result.status = AgentStatus.FAILED
                self._result.error_message = f"Database commit failed: {str(e)}"

        # Store results in context
        context["applied_corrections"] = applied_corrections
        context["failed_corrections"] = failed_corrections

        # Update metadata
        self._update_metadata("total_corrections", len(correction_actions))
        self._update_metadata("applied_corrections", len(applied_corrections))
        self._update_metadata("failed_corrections", len(failed_corrections))
        self._update_metadata("dry_run", dry_run)

        if failed_corrections:
            self.logger.warning(
                f"{len(failed_corrections)} corrections failed to apply"
            )

    def _apply_update(self, db_session: Session, correction: CorrectionAction) -> None:
        """Apply an update correction action."""
        model_class = self.MODEL_MAP.get(correction.entity_type)
        if not model_class:
            raise ValueError(f"Unknown entity type: {correction.entity_type}")

        # Get the entity
        entity = db_session.query(model_class).filter(
            model_class.id == correction.entity_id
        ).first()

        if not entity:
            raise ValueError(
                f"{correction.entity_type} with id {correction.entity_id} not found"
            )

        # Apply changes
        for field, value in correction.changes.items():
            if hasattr(entity, field):
                old_value = getattr(entity, field)
                setattr(entity, field, value)
                self.logger.debug(
                    f"Updated {correction.entity_type}.{field}: "
                    f"{old_value} -> {value}"
                )
            else:
                self.logger.warning(
                    f"Field {field} does not exist on {correction.entity_type}"
                )

        # Update timestamp
        if hasattr(entity, 'updated_at'):
            entity.updated_at = datetime.utcnow()

        correction.executed = True
        correction.success = True
        correction.timestamp = datetime.utcnow()

    def _apply_delete(self, db_session: Session, correction: CorrectionAction) -> None:
        """Apply a delete correction action."""
        model_class = self.MODEL_MAP.get(correction.entity_type)
        if not model_class:
            raise ValueError(f"Unknown entity type: {correction.entity_type}")

        # Get the entity
        entity = db_session.query(model_class).filter(
            model_class.id == correction.entity_id
        ).first()

        if not entity:
            raise ValueError(
                f"{correction.entity_type} with id {correction.entity_id} not found"
            )

        # Delete the entity
        db_session.delete(entity)
        self.logger.debug(
            f"Deleted {correction.entity_type} with id {correction.entity_id}"
        )

        correction.executed = True
        correction.success = True
        correction.timestamp = datetime.utcnow()

    def _apply_create(self, db_session: Session, correction: CorrectionAction) -> None:
        """Apply a create correction action."""
        model_class = self.MODEL_MAP.get(correction.entity_type)
        if not model_class:
            raise ValueError(f"Unknown entity type: {correction.entity_type}")

        # Create new entity with the provided data
        entity = model_class(**correction.changes)
        db_session.add(entity)
        db_session.flush()  # Get the ID

        self.logger.debug(
            f"Created {correction.entity_type} with id {entity.id}"
        )

        # Update correction with the new entity ID
        correction.entity_id = entity.id
        correction.executed = True
        correction.success = True
        correction.timestamp = datetime.utcnow()

    def get_statistics(self) -> Dict[str, Any]:
        """Get statistics about the update operations."""
        if not self._result:
            return {}

        return {
            "total_corrections": self._result.metadata.get("total_corrections", 0),
            "applied_corrections": self._result.metadata.get("applied_corrections", 0),
            "failed_corrections": self._result.metadata.get("failed_corrections", 0),
            "success_rate": (
                self._result.metadata.get("applied_corrections", 0) /
                max(self._result.metadata.get("total_corrections", 1), 1) * 100
            ),
            "dry_run": self._result.metadata.get("dry_run", False)
        }
